### ISSUE TITLE
VArec Question

### ISSUE THREAD

**Issue by agnosticlines** [angr/angr-management#1126]
### Question

Hey there, really been enjoying exploring the source code of angr-management, so many cool features that don't get enough attention!

Just saw the reference to VArec variable reconstruction, was wondering if you could share any more about how that works, is that ML based? Is it likely to ever be released?

Thanks!

**Comment by ltfish** [comment]
VARec is the frontend for our upcoming Oakland 2024 paper ["Len or index or count, anything but v1": Predicting Variable Names in Decompilation Output with Transfer Learning](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=pi3Z8FgAAAAJ&sortby=pubdate&citation_for_view=pi3Z8FgAAAAJ:k_IJM867U9cC). A pre-pub version will be ready soon. We will also release artifacts, data sets, and our trained models (and if you want to train your own models, be our guest!). It is unlikely for us to run a free-of-charge variable name prediction server just because we don't have that many free GPUs to support such a use case. You can definitely run the model locally and hook it against angr management.
