### ISSUE TITLE
Indicate to the user that they can zoom on a CFG

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-management#240]
This could take the form of floating action buttons, some text in the corner, google maps is probably not a bad place to look for inspiration.

**Comment by rhelmot** [comment]
IDA also supports zoom, through ctrl+scroll (same as us). I think the consensus about that feature is that it's a) not often necessary because IDA has the graph overview window in the corner which shows a very zoomed out view of the graph with a box to indicate the current viewport, and b) it's pretty intuitive because it copies the mechanism that browsers use. I say that if we want to make it even more intuitive, we should add `ctrl +` and `ctrl -` as zoom shortcuts as well as a View -> Zoom menu.

**Comment by ltfish** [comment]
We already solved this problem by introducing the zoom minigraph.
