### ISSUE TITLE
Should not require sqlalchemy explicitly

### ISSUE THREAD

**Issue by mborgerson** [angr/angr-management#526]
~~Only required for the CHESS plugin. This should be made optional.~~

Should specify requirement for sqlalchemy through angrdb feature requirement. See below discussion

**Comment by twizmwazin** [comment]
I believe this is actually for angr DB, git blame shows it was introduced here: https://github.com/angr/angr-management/commit/5a0abb6c7c35ff0be5dadffa5d660aa3ed5a1799. A better way is probably to specify `angr[angrDB]` instead of sqlalchemy directly. This should work with the release pipeline as-is, but I would need to verify before we merge such a change.

**Comment by ltfish** [comment]
You won’t be able to save an angr database without sqlalchemy. What’s wrong with this dependency @mborgerson ?

**Comment by mborgerson** [comment]
@ltfish I was unaware this was a requirement for angrdb and just searched the angr-management tree. Because this is not a requirement for angr-mangement, but rather a dependency for angrdb feature of angr, I think we should follow @twizmwazin's suggestion and correct the way we express this dependency to select angrDB requirements, not sqlalchemy specifically

**Comment by ltfish** [comment]
I view saving to an angrdb as a core feature of angr management. I'm not sure why we want to make this feature optional.

**Comment by twizmwazin** [comment]
@ltfish I think you misunderstand, no one is suggesting removing a core feature by default. The issue is a semantic one, angr management depends on angr's optional angrDB feature, not sqlalchemy itself. #527 updates setup.py to correct this.
